apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: weaver-ai

resources:
- namespace.yaml
- gateway/deployment.yaml
- gateway/service.yaml
- gateway/hpa.yaml
- gateway/configmap.yaml
- gateway/pdb.yaml
- redis/statefulset.yaml
- redis/service.yaml
- redis/configmap.yaml
- redis/sentinel-deployment.yaml
- ingress/ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: weaver-ai
